# Site settings
title: 'Then & Now'
email: bob@sullivanclinton.com
description: > # this means to ignore newlines until "baseurl:"
  The <em><a href="http://thenandnow.us">Then and Now</a></em> project examines three case studies of dispossession: the <em><a href="http://sullivanclinton.com" target="_blank" rel="noopener">Sullivan Clinton Campaign</a></em>, <em><a href="http://derryveagh.com" arget="_blank" rel="noopener">Derryveagh Evictions</a></em>, and <em><a href="http://stakedplains.com" arget="_blank" rel="noopener">Staked Plains</a></em>. This project is supported by the <em><a href="https://indigenousvalues.org" target="_blank" rel="noopener">Indigenous Values Initative</a></em>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thenandnow.theological.me" # the base hostname & protocol for your site
twitter_username: indigenousvalues
github_username:  adamdjbrett
logo: 'images/logo.png'

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: "/videos/"
    values:
      video: true
