# Site settings
title: 'Then & Now'
email: bob@sullivanclinton.com
description: > # this means to ignore newlines until "baseurl:"
  Supported by the Indigenous Values Initative. <a title="Sullivan-Clinton Campaign" href="http://www.sullivanclinton.com">Sullivanclinton.com</a> | <a title="Derryveagh Evictions" href="http://www.derryveagh.com">Derryveagh.com</a> | <a title="Staked Plains" href="http://www.stakedplains.com">Stakedplains.com</a>.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thenandnow.theological.me" # the base hostname & protocol for your site
twitter_username: indigenousvalues
github_username:  adamdjbrett
logo: 'images/logo.png'

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: "/videos/"
    values:
      video: true
